### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by legokichi** [Ikagaka/cuttlebone#41]
#0.1.6 (2015-5-23)
- Shell.js
  - [x] #25 canvasへの描画関連コードを Shell.jsリポに再び分ける。
  - [x] canvas由来のマウスイベントをShell.jsでハンドリングするなどのAPI再設計
    -  詳細 [Shell.js Roadmap to 5.0.0 ](https://github.com/Ikagaka/Shell.js/issues/41)
- Balloon.js
  - [x] バルーン描画関連のコードをBalloon.jsリポに分ける（現在の設計ではcanvasを主体にしていたため）
  - [x] APIを再設計して実装
- NamedManager.js
  - [x] サーフェス間クリックをどうこうする NamedManager をtsでリファクタ
- [x] cuttleboneのmasterブランチにmerge
#0.2
- [x] #39 DnDの位置
- [x] #32 メニューを表示できるように
- [x] きせかえメニュー

**Comment by legokichi** [comment]
サーフェス間の新しいレイヤ管理を試す必要ある

**Comment by legokichi** [comment]
@legokichi NamedManager rewriteが必要

**Comment by legokichi** [comment]
abee1a3ad29c20bf270952b2838d168a72f1a4cb
